<a href="https://colab.research.google.com/github/eapvithai/Command/blob/master/chapter0_pyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

resource notebook: https://www.learnpytorch.io/
if you have any question:https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [8]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cu128


##Introduction of Tensor

###Creating tensor

pytorch tensor is created by using "torch.tensor"


In [9]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [11]:
#get tensor back as Python int
scalar.item()

7

In [12]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
#this is how we find the number of dimension
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
TENSOR.ndim

3

In [20]:
 TENSOR.shape

torch.Size([1, 3, 3])